name: Build CI

on:
  schedule:
   #2AM EST == 6AM UTC
    - cron:  '0 6 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
           docker build --tag deephaven-examples/redpanda-docker-stats .
           docker-compose -f docker-compose.yml -p test-tables up -d
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1
        with:
          table-names: "docker_stats,latest_results"
          host: "envoy"
          project-name: test-tables