name: Build CI

on:
  schedule:
   #2AM EST == 6AM UTC
    - cron:  '0 6 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
           docker-compose -f docker-compose.yml -p test-tables up -d
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@main
        with:
          table-names: "docker_stats,latest_results"
          host: "envoy"
          project-name: test-tables
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.15.0
        id: notify-slack
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEVREL }}
        with:
          payload: '{"repository": "${{ github.repository }}", "message": "${{ github.workflow }}/${{ github.job }} failure", "link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'